# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# Unique collection name for this layer (IMPORTANT)
BBFILE_COLLECTIONS += "meta-riscv-core-harness"
BBFILE_PATTERN_meta-riscv-core-harness = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-riscv-core-harness = "7"

LAYERDEPENDS_meta-riscv-core-harness = "core"
LAYERSERIES_COMPAT_meta-riscv-core-harness = "scarthgap"
